### ISSUE TITLE
Banding on Kvantum Theme

### ISSUE THREAD

**Issue by sputniktr02** [vinceliuice/McMojave-kde#18]
First of all, thanks for this very polished theme.
I have some banding issue in the dark Kvantum theme. Any suggestion about what may be causing it? Or any workaround i might try?
Example:
![Screenshot_20200128_122750](https://user-images.githubusercontent.com/31340272/73251923-e9cdcf80-41ca-11ea-9b01-51b836bae5fd.jpg)

**Comment by swiatlyk** [comment]
Hi,
I have the same issue. I'm using KDE-NEON. 
![Screenshot_20200328_133504](https://user-images.githubusercontent.com/18462928/77823395-2b132a80-70fb-11ea-823d-14b6a71e32d4.png)
Do you know how to soleve this?

**Comment by swiatlyk** [comment]
Hi,
I have updated to your commit https://github.com/vinceliuice/McMojave-kde/commit/ef1fb6b3cb411854dc94fc80e8290706c6d9afb5 but this issue is still present
![Screenshot_20200330_235138](https://user-images.githubusercontent.com/18462928/77965596-a0405480-72e1-11ea-86b1-666452ca1a13.png)
I think this is more related to kvantum theme. I've downloaded this for test: https://store.kde.org/p/1252328/ and this looks ok, even with your old and new color-scheme. 
I can try to adjust your kvantum theme based on this https://store.kde.org/p/1252328/ but please tell me what parameter is backgroung.

**Comment by swiatlyk** [comment]
Hi,
I have repaired this issue (dark horizontal stripes) on some windows, like above screenshot. I just deleted line: interior.element=dialog form [Dialog] section. 
[McMojave.zip](https://github.com/vinceliuice/McMojave-kde/files/4407988/McMojave.zip)
Tell me if it's ok, and maybe you can merge it to your file.

**Comment by sputniktr02** [comment]
@vinceliuice I can confirm that the edit by @swiatlyk (Thanks mate for the solution) solves the issue for me as well.

**Comment by vinceliuice** [comment]
Thanks @swiatlyk , I'll merge this

**Comment by swiatlyk** [comment]
@vinceliuice no problem. I'm glad that I could help.

**Comment by sputniktr02** [comment]
@vinceliuice @swiatlyk Hi, do you know if it's possible to make toolbars semi-transparent like the rest of the window? (Such as in Dolphin File Manager)

**Comment by swiatlyk** [comment]
@sputniktr02 I don't know, but here is Kvantum doc, maybe you will find it what you looking for.
https://github.com/tsujan/Kvantum/blob/master/Kvantum/doc/Theme-Config
